keys:
  - &user_profiluefter 9264180E8BA8C283F19DB9F8B18AC2562696539F
  - &host_fabian-ws age1pxjza00udw4zezpzc6cdm8uqledp8mvwhmuk7y7gljqccvyjzdasj8zq26
  - &host_envy age1np7tpxyaenj2k9kn5d3keqv74u0yztshk0f05unukcpvfavryvsqsu55pd
  - &host_framework age1hjwzrlwt56v0032yjgrwyxg9ywc3gk00eer63gw6z390mplsz3wskxnwka

creation_rules:
  - key_groups:
      - pgp:
          - *user_profiluefter
        age:
          - *host_fabian-ws
          - *host_envy
          - *host_framework
